### ISSUE TITLE
Memory usage is too high

### ISSUE THREAD

**Issue by Shivam101** [tbaranes/FittableFontLabel#14]
Hello,

I am importing and using FittableFontLabel into my project. While it is certainly very useful, the memory usage in-app due to library is very high. My app frequently hangs(and eventually force closes) since I have imported this. 

I see in `What's next` that something is being done regarding this? 

Thanks!

**Comment by tbaranes** [comment]
There's any fix coming for this. I have to take a deeper look to understand what the is _the real_ issue.
I'm not sure that I will have time to fix this soon (busy at work), but if you want to submit a PR, I will definitely review it 🙃

One thing that could improve the memory usage would be to use binary search instead of the current loop, it should be cheaper in memory and faster.

Wondering if that issue is not also related to #11

**Comment by tbaranes** [comment]
@Shivam101 Just pushed a branch implementing the binary search algorithm (#17). That should be improved the `FittableFontLabel` performance, can you give a try?

Since it's testing less fonts, the memory usage should be better. If you still have issues with it, can you give any instrument's screenshots / leads in order to improve it?

**Comment by tbaranes** [comment]
Just merged the binary search, I'm closing this now. If you find the memory usage is still too hight, we will reopen it   👍
